const fs = require('node:fs');
const path = require('node:path');
const { describe, expect, it } = require('@jest/globals');

const migrationPath = path.resolve(
  process.cwd(),
  'supabase/migrations/00000000000001_account_progress.sql',
);
const pgTapPath = path.resolve(
  process.cwd(),
  'supabase/tests/database/account_progress_rls.test.sql',
);

function migration() {
  expect(fs.existsSync(migrationPath)).toBe(true);
  return fs.readFileSync(migrationPath, 'utf8').toLowerCase();
}

function pgTapTest() {
  expect(fs.existsSync(pgTapPath)).toBe(true);
  return fs.readFileSync(pgTapPath, 'utf8').toLowerCase();
}

describe('account progress database contract', () => {
  it('stores only minimal profiles and question completion identity', () => {
    const sql = migration();

    expect(sql).toContain('create table public.profiles');
    expect(sql).toContain('references auth.users (id) on delete cascade');
    expect(sql).toContain('create table public.user_question_progress');
    expect(sql).toContain("catalog_version text not null check (catalog_version = '17dd300a')");
    expect(sql).toContain('question_ordinal integer not null');
    expect(sql).toContain('check (question_ordinal between 1 and 500)');
    expect(sql).toContain('primary key (user_id, catalog_version, question_ordinal)');
    expect(sql).not.toContain('generated by default as identity');
    expect(sql).not.toContain('user_question_progress_id_seq');
    expect(sql).not.toContain('marketing');
    expect(sql).not.toContain('answer_text');
  });

  it('enables RLS and limits profile and progress rows to auth.uid()', () => {
    const sql = migration();

    expect(sql).toContain('alter table public.profiles enable row level security');
    expect(sql).toContain('alter table public.profiles force row level security');
    expect(sql).toContain('alter table public.user_question_progress enable row level security');
    expect(sql).toContain('alter table public.user_question_progress force row level security');
    expect(sql.match(/auth\.uid\(\) = id/g)?.length).toBeGreaterThanOrEqual(1);
    expect(sql.match(/auth\.uid\(\) = user_id/g)?.length).toBeGreaterThanOrEqual(2);
    expect(sql).toContain('revoke all on table public.profiles from anon');
    expect(sql).toContain('revoke all on table public.user_question_progress from anon');
  });

  it('exposes progress only through the atomic authenticated RPC', () => {
    const sql = migration();

    expect(sql).toContain('revoke all on table public.profiles from authenticated');
    expect(sql).toContain('revoke all on table public.user_question_progress from authenticated');
    expect(sql).toContain('grant select on table public.profiles to authenticated');
    expect(sql).not.toContain('grant select on table public.user_question_progress to authenticated');
    expect(sql).not.toContain('grant insert (catalog_version, question_ordinal, completed_at) on table public.user_question_progress to authenticated');
    expect(sql).not.toContain('grant select, insert, update, delete');
    expect(sql).not.toContain('progress_update_own');
    expect(sql).not.toContain('progress_delete_own');
  });

  it('binds atomic synchronization to the expected authenticated user', () => {
    const sql = migration();

    expect(sql).toContain('create or replace function public.sync_account_progress');
    expect(sql).toContain('expected_user_id uuid');
    expect(sql).toContain('requested_catalog_version text');
    expect(sql).toContain('completion_rows jsonb');
    expect(sql).toContain('if auth.uid() is distinct from expected_user_id then');
    expect(sql).toContain("if requested_catalog_version is distinct from '17dd300a' then");
    expect(sql).toContain("raise exception 'account identity changed during synchronization'");
    expect(sql).toContain('on conflict on constraint user_question_progress_pkey do nothing');
    expect(sql).not.toContain('on conflict (user_id, catalog_version, question_ordinal)');
    expect(sql).toContain('revoke all on function public.sync_account_progress(uuid, text, jsonb) from public');
    expect(sql).toContain('grant execute on function public.sync_account_progress(uuid, text, jsonb) to authenticated');
    expect(sql).not.toContain('grant execute on function public.sync_account_progress(uuid, text, jsonb) to anon');
  });

  it('defines authenticated self-service export and deletion without direct auth-table access', () => {
    const sql = migration();

    expect(sql).toContain('function public.export_account_data(');
    expect(sql).toContain('function public.delete_own_account(');
    expect(sql).toContain("if auth.uid() is distinct from expected_user_id then");
    expect(sql).toContain("'schema_version', 1");
    expect(sql).toContain('delete from auth.users where id = expected_user_id');
    expect(sql).toContain('grant execute on function public.export_account_data(uuid) to authenticated');
    expect(sql).toContain('grant execute on function public.delete_own_account(uuid) to authenticated');
    expect(sql).not.toContain('grant execute on function public.delete_own_account(uuid) to anon');
  });

  it('keeps the executable pgTAP plan aligned with the declared plan', () => {
    const sql = pgTapTest();

    expect(sql).toContain('select plan(25)');
    expect(sql).toContain('clients cannot bypass atomic synchronization with direct progress reads');
    expect(sql).toContain('clients cannot bypass atomic synchronization with direct progress inserts');
    expect(sql).toContain('a user cannot set the ownership column to their own id');
    expect(sql).toContain("a user cannot update another user's progress");
    expect(sql).toContain("a user cannot delete another user's progress");
    expect(sql).toContain('an owner can atomically sync their own progress');
    expect(sql).toContain('an account switch cannot write the prior account progress');
    expect(sql).toContain('anonymous sessions cannot execute account synchronization');
  });

  it('creates profiles from verified auth identities and cascades account deletion', () => {
    const sql = migration();

    expect(sql).toContain('create trigger on_auth_user_created');
    expect(sql).toContain('after insert on auth.users');
    expect(sql).toContain('execute function public.handle_new_user()');
    expect(sql.match(/on delete cascade/g)?.length).toBeGreaterThanOrEqual(2);
  });
});
